/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Fri Feb 24 13:36:24 2017. */

#include "protocols.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CanMessage_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CanMessage, TimeStamp, TimeStamp, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, Header, TimeStamp, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, ID, Header, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, Data1, ID, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, Data2, Data1, 0),
    PB_LAST_FIELD
};

const pb_field_t ControlMessage_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, ControlMessage, Parameter, Parameter, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, ControlMessage, Value, Parameter, 0),
    PB_LAST_FIELD
};

const pb_field_t UsbMessage_fields[3] = {
    PB_ONEOF_FIELD(payload,   1, MESSAGE , ONEOF, STATIC  , FIRST, UsbMessage, ControlMsg, ControlMsg, &ControlMessage_fields),
    PB_ONEOF_FIELD(payload,   2, MESSAGE , ONEOF, STATIC  , FIRST, UsbMessage, CanMsg, CanMsg, &CanMessage_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(UsbMessage, payload.ControlMsg) < 65536 && pb_membersize(UsbMessage, payload.CanMsg) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_CanMessage_ControlMessage_UsbMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(UsbMessage, payload.ControlMsg) < 256 && pb_membersize(UsbMessage, payload.CanMsg) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_CanMessage_ControlMessage_UsbMessage)
#endif


/* @@protoc_insertion_point(eof) */
